
- name: Grid Setup
  block:
    - name: install grid.rsp
      template:
        src: grid.no.comments.rsp
        dest: /oracle/u01/gi/grid.rsp
        mode: '0644'
    - shell: "./gridSetup.sh -silent -responseFile /oracle/u01/gi/grid.rsp"
      args:
        chdir: "/oracle/u01/gi/{{ oracle_ver_path }}"
        creates: "/oracle/u01/oraInventory"
      ignore_errors: true
      register: grid_setup_out
    - debug: 
        msg: "Return code is {{ grid_setup_out.rc }}"
      when: grid_setup_out.rc >= 2

  rescue:
    - debug:
        msg: '"./gridSetup.sh failed'
    - name: delete response file
      file:
        path: /oracle/u01/gi/grid.rsp
        state: absent

  become: yes
  become_user: oracle
