---
# sysctl file for oraclebase

- sysctl:
    name: kernel.shmmni
    value: "4096"
    sysctl_file: /etc/sysctl.d/98-oracle.conf

- sysctl:
    name: kernel.sem
    value: "1010 129280 1010 128"
    sysctl_file: /etc/sysctl.d/98-oracle.conf

- sysctl:
    name: fs.file-max
    value: "6815744"
    sysctl_file: /etc/sysctl.d/98-oracle.conf

- sysctl:
    name: net.ipv4.ip_local_port_range
    value: "9000 65501"
    sysctl_file: /etc/sysctl.d/98-oracle.conf

- sysctl:
    name: net.core.rmem_default
    value: "262144"
    sysctl_file: /etc/sysctl.d/98-oracle.conf

- sysctl:
    name: net.core.rmem_max
    value: "4194304"
    sysctl_file: /etc/sysctl.d/98-oracle.conf

- sysctl:
    name: net.core.wmem_default
    value: "262144"
    sysctl_file: /etc/sysctl.d/98-oracle.conf

- sysctl:
    name: net.core.wmem_max
    value: "1048576"
    sysctl_file: /etc/sysctl.d/98-oracle.conf

- sysctl:
    name: fs.aio-max-nr
    value: "4194304"
    sysctl_file: /etc/sysctl.d/98-oracle.conf

- sysctl:
    name: kernel.panic_on_oops
    value: "1"
    sysctl_file: /etc/sysctl.d/98-oracle.conf

- sysctl:
    name: kernel.shmall
    value: "{{ shma }}"
    sysctl_file: /etc/sysctl.d/98-oracle.conf

- sysctl:
    name: kernel.shmmax
    value: "{{ shmm }}"
    reload: yes
    sysctl_file: /etc/sysctl.d/98-oracle.conf

# PRCF-2010 : All connections to the remote nodes got refused. 
- sysctl:
    name: net.ipv6.bindv6only
    value: 0
    reload: yes
    sysctl_file: /etc/sysctl.d/98-oracle.conf

# https://access.redhat.com/documentation/en-us/reference_architectures/2017/html-single/deploying_oracle_rac_database_12c_release_2_on_red_hat_enterprise_linux_7/index#kernel_parameters
- sysctl:
    name: vm.swappiness
    value: 1
    sysctl_file: /etc/sysctl.d/98-oracle.conf

- sysctl:
    name: vm.dirty_background_ratio
    value: 3
    sysctl_file: /etc/sysctl.d/98-oracle.conf

- sysctl:
    name: vm.dirty_ratio
    value: 80
    sysctl_file: /etc/sysctl.d/98-oracle.conf

- sysctl:
    name: vm.dirty_expire_centisecs
    value: 500
    sysctl_file: /etc/sysctl.d/98-oracle.conf

- sysctl:
    name: vm.dirty_writeback_centisecs
    value: 100
    sysctl_file: /etc/sysctl.d/98-oracle.conf
