
- block:
    - name: Download install package
      get_url:
        url: http://192.168.8.200/oracle/{{ oracle_major_version }}/{{ oracle_install_package_name }}
        dest: /home/oracle/
        mode: '0640'

    - name: unzip install package
      unarchive:
        src: /home/oracle/{{ oracle_install_package_name }}
        dest: /home/oracle/
        remote_src: yes

    - name: delete install .zip package
      file:
        path: /home/oracle/{{ oracle_install_package_name }}
        state: absent

  become: yes
  become_user: oracle


