# oracle database 12R1

- name: DB Home Setup
  block:

    - name: install db.rsp
      template:
        src: db.no.comments.rsp
        dest: /home/oracle/db.rsp
        mode: '0640'
        owner: oracle
        group: oinstall

    - shell: "./runInstaller -responseFile /home/oracle/db.rsp -waitForCompletion -silent -ignorePrereq"
      args:
        chdir: "/home/oracle/database"
        creates: "/oracle/u01/db/{{ oracle_ver_path }}/bin/oracle"
      ignore_errors: true
      register: db_setup_out
    - debug: 
        msg: "Return code is {{ db_setup_out }}"
    - debug:
        msg: "Return code is {{ db_setup_out.rc }}"
      when: db_setup_out.rc >= 0

  rescue:
    - name: delete install directory
      file:
        path: "/home/oracle/database"
        state: absent

    - name: delete install db.rsp
      file:
        path: /home/oracle/db.rsp
        state: absent

    - fail:
        msg: './runInstaller failed'

  become: yes
  become_user: oracle

- name: delete install directory
  file:
    path: "/home/oracle/database"
    state: absent
