---
# vars file for oraclerestart

oracle_major_version: "12.2"

# Note: there is dependecy between this and grid.rsp
# Base install package does not support
#  oracle.install.crs.configureGIMR=true
# While pathed Golden image does
#oracle_install_package_name: "linuxx64_12201_grid_home.zip"
oracle_install_package_names: ["grid_home_2019-06-24_08-33-38PM.zip"]

oracle_ver_path: "12.2.0.1"

asm_disks: []
asm_disk_partitions: []
