---
# tasks file for oracledatabase 19c

- include: os.setup.yml

- name: "ora_2_env file"
  template:
    src: ora_2_env
    dest: "/home/oracle/.ora_2_env"
    owner: oracle
    group: oinstall

- name: "DB fome"
  file:
    path: "/oracle/u01/db"
    state: directory
    owner: oracle
    group: oinstall
#    recurse: yes
#    mode: '0755'

- name: "DB fome"
  file:
    path: "/oracle/u01/db/{{ oracle_ver_path }}"
    state: directory
    owner: oracle
    group: oinstall
#    recurse: yes
#    mode: '0755'

- name: install db.rsp
  template:
    src: db.no.comments.rsp
    dest: /home/oracle/db.rsp
    mode: '0644'
    owner: oracle
    group: oinstall

- name: check if install package exists
  stat: 
    path: /oracle/u01/db/{{ oracle_ver_path }}/bin
  register: install_package
  
- debug:
    msg: "Install package exists: {{ install_package.stat.exists }}"

- include: download.package.yml
  when: ansible_hostname == first_rac_node and install_package.stat.exists != True

- include: setup.db.yml
  when: ansible_hostname == first_rac_node

- name: db root.sh
  shell: "/oracle/u01/db/{{ oracle_ver_path }}/root.sh"
  args:
    chdir: "/"
    creates: "/opt/ORCLfmap/prot1_64/bin/fmputl"
  ignore_errors: true

- name: check if database was created
  stat:
    path: /oracle/u01/base/cfgtoollogs/dbca/{{ oracle_sid }}/{{ oracle_sid }}.log
  register: dcdba_log

- debug:
    msg: "Database exists: {{ dcdba_log.stat.exists }}"

- include: create_database.yml
  when: ansible_hostname == first_rac_node and dcdba_log.stat.exists != True
