
- name: udev 55
  copy:
    src: 55-usm.rules
    dest: /etc/udev/rules.d/55-usm.rules

- name: udev 12
  copy:
    src: 12-dm-permissions.rules
    dest: /etc/udev/rules.d/12-dm-permissions.rules

- name: udev 10
  copy:
    src: 10-scsi-asm.rules
    dest: /etc/udev/rules.d/10-scsi-asm.rules

- name: install udevasm.sh
  copy:
    src: udevasm.sh
    dest: /etc/udev/udevasm.sh
    mode: '0750'

- name: reload udev
  command: udevadm trigger

- name: Wait for ASM DISK detection (part I)
  wait_for:
    path: /dev/asmshared000
    delay: 0
    timeout: 30
    state: present

- name: Wait for ASM DISK detection (part II)
  wait_for:
    path: /dev/asmshared001
    delay: 0
    timeout: 30
    state: present

# - name: ASM paritions detected
#   debug: 
#     msg: "ASM DISKs {{ asm_disks }}"

# - debug:
#     var: item.path
#   with_items: "{{ asm_disks.files }}"

- name: list files
  find:
    paths: /dev/
    patterns: "asmshared[0-9][0-9][0-9]"
    file_type: link
  register: _asm_disks

- debug:
    msg: "{{ item.path }}"
  with_items: "{{ _asm_disks.files }}"

- name: Build a list of all ASM disks
  set_fact:
    asm_disks : "{{ asm_disks }} + [ '{{ item.path }}' ]"
  with_items: "{{ _asm_disks.files }}"

- debug:
    var: asm_disks

- name: ASM paritions
  parted:
    device: "{{item}}"
    label: gpt
    number: 1
    state: present
  with_items: "{{ asm_disks }}"

- name: list files
  find:
    paths: /dev/
    patterns: "asmshared[0-9][0-9][0-9]p1"
    file_type: link
  register: _asm_disk_partitions

- name: Build a list of all ASM partitions
  set_fact:
    asm_disk_partitions : "{{ asm_disk_partitions }} + [ '{{ item.path }}' ]"
  with_items: "{{ _asm_disk_partitions.files }}"

- debug:
    var: asm_disk_partitions

- debug:
    msg: "{{ item }}"
  with_items: "{{ _asm_disk_partitions }}"
