# fqdn.yml
---
- shell: "ssh -oStrictHostKeyChecking=no {{ item }} hostname -f"
  register: fqdn
  become: yes
  become_user: oracle
- debug: var=fqdn.stdout_lines
- set_fact:
    crs_nodes_fqdn: "{{ crs_nodes_fqdn + [ fqdn.stdout_lines[0] ] }}"
- debug: var=crs_nodes_fqdn

# TODO other way using dig  vars:
#     ip: "{{ lookup('dig', item ) }}"
#     fqdn: "{{ lookup('dig', ip, 'qtype=PTR' ) }}"
#     with_items:
#     - "{{ ansible_play_batch }}"
# - set_fact:
#     target_ip: "{{ lookup('dig', 'rhel7-rac-a-node-1') }}"
# - debug:
#     var: target_ip
# - set_fact:
#     target_fqdn: "{{ lookup('dig', target_ip ) }}"
# - debug:
#     var: target_fqdn
