
- name: Grid Setup
  block:
    - name: install grid.rsp
      template:
        src: grid.phase.0.rsp
        dest: /oracle/u01/gi/grid.rsp
        mode: '0644'

    - name: ACFS Centos path
      copy:
        src: acfs.centos.patch
        dest: /oracle/u01/gi/{{ oracle_ver_path }}/lib/

    - name: Apply patch ACFS Centos patch
      patch:
        src: acfs.centos.patch
        basedir: /oracle/u01/gi/{{ oracle_ver_path }}/lib/
        strip: 0

    - name: "gridSetup.sh (part I)"
      shell: "./gridSetup.sh -silent -responseFile /oracle/u01/gi/grid.rsp"
      args:
        chdir: "/oracle/u01/gi/{{ oracle_ver_path }}"
        creates: "/oracle/u01/oraInventory/oraInst.loc"
      ignore_errors: true
      register: grid_setup_out
    - debug: 
        msg: "gridSetup.sh (part I) {{ grid_setup_out }}"
      when: grid_setup_out.rc >= 2
    - debug: 
        msg: "Return code is {{ grid_setup_out.rc }}"
      when: grid_setup_out.rc >= 2

  rescue:
    - debug:
        msg: '"./gridSetup.sh failed'
    - name: delete install .zip package
      file:
        path: /oracle/u01/gi/grid.rsp
        state: absent

  become: yes
  become_user: oracle
  when: ansible_hostname == first_rac_node

