---
# tasks file for oracledatabase 19c

- name: delete response file
  file:
    path: /home/oracle/db.rsp
    state: absent

- name: check if oracle home installed
  stat:
    path: "/oracle/u01/db/{{ oracle_ver_path }}/bin/extjob"
  register: oracle_home_installed

- debug:
    msg: "Oracle home installed: {{ oracle_home_installed.stat.exists }}"

- name: "ora_2_env file"
  template:
    src: ora_2_env
    dest: "/home/oracle/.ora_2_env"
    owner: oracle
    group: oinstall

- name: "DB home (ORACLE_HOME directory)"
  file:
    path: "/oracle/u01/db/{{ oracle_ver_path }}"
    state: directory
    owner: oracle
    group: oinstall
    recurse: yes
    mode: '0755'
  when: oracle_home_installed.stat.exists != True

- name: check if install package exists
  stat: 
    path: /oracle/u01/db/{{ oracle_ver_path }}/bin
  register: install_package
  
- debug:
    msg: "Install package exists: {{ install_package.stat.exists }}"

- name: Include Role oracle.download.package
  include_role:
    name: oracle.download.package
  vars:
    oracle_home: "/oracle/u01/db/{{ oracle_ver_path }}"
  when: oracle_home_installed.stat.exists != True and install_package.stat.exists != True

- include: setup.db.yml
  when: oracle_home_installed.stat.exists != True

- name: db root.sh
  shell: "/oracle/u01/db/{{ oracle_ver_path }}/root.sh"
  args:
    chdir: "/"
    creates: "/oracle/u01/db/{{ oracle_ver_path }}/bin/extjob"
  ignore_errors: true

- name: "DBA home"
  file:
    path: "/oracle/u01/db/{{ oracle_ver_path }}/DBA"
    state: directory
    owner: oracle
    group: oinstall
    mode: '0755'

- name: check if database was created
  stat:
    path: /oracle/u01/base/cfgtoollogs/dbca/{{ oracle_sid }}/{{ oracle_sid }}.log
  register: dcdba_log

- debug:
    msg: "Database exists: {{ dcdba_log.stat.exists }}"

- include: create_database.yml
  when: dcdba_log.stat.exists != True
