
- name: DB Home Setup
  block:
    - name: install db.rsp
      copy:
        src: db.rsp
        dest: /oracle/u01/db/db.rsp
        mode: '0644'
    - shell: "./runInstaller -responseFile /oracle/u01/db/db.rsp -silent"
      args:
        chdir: "/oracle/u01/db/{{ oracle_ver_path }}"
        creates: "/oracle/u01/db/{{ oracle_ver_path }}/oraInst.loc"
      ignore_errors: true
      register: db_setup_out
    - debug: 
        msg: "Return code is {{ db_setup_out }}"
      when: db_setup_out.rc >= 0
    - debug: 
        msg: "Return code is {{ db_setup_out.rc }}"
      when: db_setup_out.rc >= 0

    # - name: "Goldem image fixups - missing dirs"
    #   file:
    #     path: "/oracle/u01/gi/12.2.0.1/{{item}}"
    #     state: directory
    #     recurse: yes
    #   with_items: ["cdata", "cdata/localhost", "crs/init", "crs/log", "evm/init", "log", "log/crs", "racg/dump", "srvm/log"]

  rescue:
    - debug:
        msg: './runInstaller failed'
    - name: delete install db.rsp
      file:
        path: /oracle/u01/db/db.rsp
        state: absent

  become: yes
  become_user: oracle
