
- name: DB Home Setup
  block:
    - name: install db.rsp
      template:
        src: db.no.comments.rsp
        dest: /oracle/u01/db/db.rsp
        mode: '0640'
        owner: oracle
        group: oinstall

    - shell: "./runInstaller -responseFile /oracle/u01/db/db.rsp -silent"
      args:
        chdir: "/oracle/u01/db/{{ oracle_ver_path }}"
        creates: "/oracle/u01/db/{{ oracle_ver_path }}/oraInst.loc"
      ignore_errors: true
      register: db_setup_out
    - debug: 
        msg: "Return code is {{ db_setup_out }}"
    - debug:
        msg: "Return code is {{ db_setup_out.rc }}"
      when: db_setup_out.rc >= 0

  rescue:
    - debug:
        msg: './runInstaller failed'
    - name: delete install db.rsp
      file:
        path: /oracle/u01/db/db.rsp
        state: absent

  become: yes
  become_user: oracle
