
- name: Set authorized key took from file
  authorized_key:
    user: oracle
    state: present
    key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"

- name: ensure private key and public one are present
  copy: 
    src: keys/
    dest: "/home/oracle/.ssh/"
    mode: 0400
    owner: oracle
    group: oinstall
  with_items:
    - id_rsa

- name: Accept ssh keys from all other cluster nodes
  shell: "ssh -oStrictHostKeyChecking=no {{ item }} hostname"
  become: yes
  become_user: oracle
  with_items:
    - "{{ ansible_play_batch }}"
      
- name: 'Extend the u01'
  lvol:
    vg: vg01
    lv: u01
    size: 50G
    shrink: no
    resizefs: yes

- name: Oracle CRS required packages
  yum: 
    name=device-mapper-multipath,ksh,sysstat,smartmontools,gcc-c++,net-tools
    state=latest

- name: Oracle CRS required packages
  yum: 
    name=cvuqdisk
    state=latest
    disable_gpg_check=yes 

- name: "Oracle KB"
  file:
    path: "/home/oracle/.ORACLE_KB"
    state: directory
    owner: oracle
    group: oinstall

- name: "Gi fome"
  file:
    path: "/oracle/u01/gi/{{ oracle_ver_path }}"
    state: directory
    owner: oracle
    group: oinstall
    recurse: yes
    mode: '0755'
