---
# post instalation tasks 

- name: Oracle profile
  yum:
    name=haf-oracle-profile,haf-oracle-rlwrap
    state=latest
    disable_gpg_check=yes

- name: delete install grid.rsp
  file:
    path: /oracle/u01/gi/grid.rsp
    state: absent

- name: delete install directory
  file:
    path: /home/oracle/grid
    state: absent

- name: delete install directory
  file:
    path: /home/oracle/database
    state: absent

- name: delete install db.rsp
  file:
    path: /home/oracle/db.rsp
    state: absent

- name: delete install dbca.rsp
  file:
    path: /home/oracle/dbca.rsp
    state: absent
