---
# vars file for oraclerestart

oracle_major_version: "19"

# Note: there is dependecy between this and grid.rsp
# Base install package does not support
#  oracle.install.crs.configureGIMR=true
# While pathed Golden image does
#oracle_install_package_name: "LINUX.X64_193000_grid_home.zip"
oracle_install_package_names: ["grid_home_2020-02-29_03-04-07PM.zip"]

oracle_ver_path: "19.5.0.0"

first_rac_node: "{{ ansible_play_batch[0] }}"
