
- block:
    - debug:
        msg: "Unpack into {{ oracle_home }}"
    - name: Download install package {{ item }}
      get_url:
        url: http://192.168.8.200/oracle/{{ oracle_major_version }}/{{ item }}
        dest: /oracle/u01/
        mode: '0640'

    - name: "ORACLE_HOME gi/db"
      file:
        path: "{{ oracle_home }}"
        state: directory
        owner: oracle
        group: oinstall
        recurse: yes
        mode: '0755'

    - name: unzip install package {{ item }}
      unarchive:
        src: /oracle/u01/{{ item }}
        dest: "{{ oracle_home }}"
        remote_src: yes

    - name: delete install .zip package {{ item }}
      file:
        path: /oracle/u01/{{ item }}
        state: absent

  become: yes
  become_user: oracle
