
- name: Grid Setup
  block:
    - name: install grid.rsp
      template:
        src: grid.no.comments.rsp
        dest: /home/oracle/grid.rsp
        mode: '0640'
        owner: oracle

    - name: "gridSetup.sh (part I)"
      shell: "./gridSetup.sh -silent -responseFile /home/oracle/grid.rsp"
      args:
        chdir: "/oracle/u01/gi/{{ oracle_ver_path }}"
        creates: "/oracle/u01/oraInventory/oraInst.loc"
      ignore_errors: true
      register: grid_setup_out
    - debug: 
        msg: "Return code is {{ grid_setup_out.rc }}"
      when: grid_setup_out.rc >= 2

  rescue:
    - name: delete response file
      file:
        path: /home/oracle/grid.rsp
        state: absent

    - fail:
        msg: '"./gridSetup.sh failed'

  become: yes
  become_user: oracle
