
- name: Grid Setup
  block:
    - name: install grid.rsp
      template:
        src: grid.no.comments.rsp
        dest: /home/oracle/grid.rsp
        mode: '0644'

    - shell: "./gridSetup.sh -silent -responseFile /home/oracle/grid.rsp"
      args:
        chdir: "/oracle/u01/gi/{{ oracle_ver_path }}"
        creates: "/oracle/u01/oraInventory"
      ignore_errors: true
      register: grid_setup_out
    - debug: 
        msg: "Return code is {{ grid_setup_out.rc }}"
      when: grid_setup_out.rc >= 2

    - name: "Goldem image fixups - missing dirs"
      file:
        path: "/oracle/u01/gi/12.2.0.1/{{item}}"
        state: directory
        recurse: yes
      with_items: ["cdata", "cdata/localhost", "crs/init", "crs/log", "evm/init", "log", "log/crs", "racg/dump", "srvm/log"]

  rescue:
    - debug:
        msg: '"./gridSetup.sh failed'
    - name: delete response file
      file:
        path: /home/oracle/grid.rsp
        state: absent

  become: yes
  become_user: oracle
